-- Create a table for like
create table bot_like (
  id bigint not null generated by default as identity,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  voter_uid uuid references auth.users not null,
  bot_uid uuid references public.bots not null,
  positive boolean default true,

  primary key (id),
  unique (voter_uid, bot_uid)
);

alter table bot_like enable row level security;

create policy "Public like are viewable by everyone."
  on bot_like for select
  using ( true );

create policy "Users can insert their own like."
  on bot_like for insert
  with check ( auth.uid() = voter_uid );

create policy "Users can update own like."
  on bot_like for update
  using ( auth.uid() = voter_uid );

-- Set up Realtime!
-- begin;
--   drop publication if exists supabase_realtime;
--   create publication supabase_realtime;
-- commit;
-- alter publication supabase_realtime add table profiles;
