-- Create a table for tag
create table bots (
  id int generated by default as identity not null,
  updated_at timestamp with time zone default now(),
  created_at timestamp with time zone default now(),
  tag_description text not null;
  tag_name text not null;

  primary key (id),
  unique(tag_name)
);

alter table tag enable row level security;

create policy "Public tags are viewable by everyone."
  on tag for select
  using ( true );
